In [ ]:
import tensorflow as tf

In [1]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Things you should automatically know and have memorized
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [3]:
# Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [4]:
# Make an RNN
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [5]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

[[-0.52115417 -0.04933101]]


In [6]:
# See if we can replicate this output
# Get the weights first
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 5)                 45        
_________________________________________________________________
dense (Dense)                (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [7]:
# See what's returned
model.layers[1].get_weights()

[array([[-0.30886745,  0.20398742, -0.8007836 , -0.7232545 ,  0.59697896],
        [-0.61858225,  0.02082253, -0.17112345, -0.08437377,  0.7796251 ],
        [-0.64751726,  0.44246477, -0.17179221,  0.15382022, -0.84645224]],
       dtype=float32),
 array([[ 0.6902031 , -0.17909592, -0.30066037,  0.2264912 ,  0.59148073],
        [-0.58573824,  0.16163652, -0.26151267,  0.6661577 ,  0.3444261 ],
        [-0.35560766, -0.6265339 , -0.5295103 , -0.43119207,  0.12120476],
        [-0.00127526, -0.7407448 ,  0.4816601 ,  0.4442631 , -0.14808552],
        [ 0.23253392, -0.02346182, -0.57344306,  0.34876844, -0.70349216]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [8]:
# Check their shapes
# Should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [9]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [10]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  
  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[-0.5211541  -0.04933103]
