# **Arrays vs Lists**

In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)
L

[1, 2, 3, 4]

In [7]:
# Illegal operation
# A.append(4)

AttributeError: ignored

In [8]:
L + [5]

[1, 2, 3, 4, 5]

In [9]:
# Each item is added by 4, operation called broadcasting
A + np.array([4])

array([5, 6, 7])

In [11]:
# Vector addition
A + np.array([4, 5, 6])

array([5, 7, 9])

In [12]:
# Illegal - different sizes
# A + np.array([4, 5])

ValueError: ignored

In [13]:
2 * A

array([2, 4, 6])

In [14]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
L2 = []
for e in L:
  L2.append(e + 3)

In [18]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [19]:
# Illegal
# L**2

TypeError: ignored

In [21]:
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

In [22]:
A**2 

array([1, 4, 9])

In [23]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [25]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [ ]:
# Lists - looks like an array but works like a data structure
# Arrays - np.array funcions as an array for math problems

# **The Dot Product**

In [26]:
a = np.array([1, 2])
b = np.array([3, 4])

In [28]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
dot

11

In [29]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [31]:
a * b
np.sum(a*b)

11

In [32]:
(a*b).sum()

11

In [33]:
np.dot(a,b)

11

In [34]:
a.dot(b)

11

In [35]:
a @ b

11

In [37]:
# Other formula
amag = np.sqrt((a*a).sum())
# or it is the same
amag = np.linalg.norm(a)

2.23606797749979

In [38]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [39]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

# **Matrices**

In [40]:
L = [[1,2], [3, 4]]
L

[[1, 2], [3, 4]]

In [43]:
L[0][1]

2

In [46]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [47]:
A[0][1]

2

In [48]:
A[0,1]

2

In [49]:
A[:,0]

array([1, 3])

In [51]:
A.T

array([[1, 3],
       [2, 4]])

In [52]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [53]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [54]:
B = np.array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [56]:
# Illegal - doesn't match dimensions
# A.dot(B.T)

ValueError: ignored

In [57]:
np.linalg.det(A)

-2.0000000000000004

In [58]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [59]:
np.trace(A)

5

In [60]:
np.diag(A)

array([1, 4])

In [61]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [63]:
Lam, V = np.linalg.eig(A)

In [64]:
V[:, 0] * Lam[0] == A @ V[:, 0]

array([ True, False])

In [65]:
V[:, 0] * Lam[0], A @ V[:, 0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [66]:
# Use np.allclose instead of ==
np.allclose(V[:, 0] * Lam[0], A @ V[:, 0])

True

In [67]:
np.allclose(V @ np.diag(Lam), A @ V)

True

# **Solving Linear Systems**

ex: 
* x1 + x2 = 2200
* 1.5x1 + 4x2 = 5050

In [68]:
A = np.array([[1,1], [1.5, 4]])
b = np.array([2200, 5050])

In [69]:
np.linalg.solve(A, b)

array([1500.,  700.])

# **Generating Data**

In [70]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [74]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.random.random()

0.1969247645241856

In [76]:
np.random.random((2, 3))

array([[0.95416884, 0.20541519, 0.53862739],
       [0.83553718, 0.317482  , 0.74955683]])

In [77]:
# Gaussian (0, 1)
np.random.randn(2, 3)

array([[ 0.44280922,  0.9371125 , -0.2073239 ],
       [-0.2749787 , -0.9699182 , -0.32289452]])

In [78]:
R = np.random.randn(10000)

In [79]:
R.mean()

0.006892408425178644

In [80]:
np.mean(R)

0.006892408425178644

In [81]:
R.var()

1.0119289424309197

In [82]:
R.std()

1.005946789065366

In [83]:
R = np.random.randn(10000, 3)

In [84]:
R.mean(axis = 0)

array([0.00212875, 0.00181159, 0.02767114])

In [87]:
R.mean(axis = 1).shape

(10000,)

In [88]:
np.cov(R).shape

(10000, 10000)

In [89]:
np.cov(R, rowvar=False)

array([[ 0.99962682, -0.01035228,  0.01278642],
       [-0.01035228,  0.99319581,  0.00562448],
       [ 0.01278642,  0.00562448,  0.97584243]])

In [90]:
np.random.randint(0, 10, size=(3, 3))

array([[0, 8, 7],
       [7, 9, 0],
       [8, 3, 8]])

In [91]:
np.random.choice(10, size=(3, 3))

array([[8, 9, 3],
       [4, 7, 3],
       [1, 9, 7]])